
CONTIKI=../../contiki-ng

# Include CoAP resources
# MODULES_REL += ../_resources
CONTIKI_PROJECT = rm-pn532
MODULES_REL += ../pn532-lib

all: $(CONTIKI_PROJECT)

include ../Makefile.common

include $(CONTIKI)/Makefile.include
