
CONTIKI=../../contiki-ng

# Include CoAP resources
# MODULES_REL += ../_resources
CONTIKI_PROJECT = rm-dlock

all: $(CONTIKI_PROJECT)

include ../Makefile.common

include $(CONTIKI)/Makefile.include
